// this is a array map for the condition code defined with yahoo see: https://developer.yahoo.com/weather/documentation.html
const weatherConditionMap = [
    'Tornado',
    'Tropical storm',
    'Hurricane',
    'Severe thunderstorms',
    'Thunderstorms',
    'Mixed rain and snow',
    'Mixed rain and sleet',
    'Mixed snow and sleet',
    'Freezing drizzle',
    'Drizzle',
    'Freezing rain',
    'Showers',
    'Showers',
    'Snow flurries',
    'Light snow showers',
    'Blowing snow',
    'Snow',
    'Hail',
    'Sleet',
    'Dust',
    'Foggy',
    'Haze',
    'Smoky',
    'Blustery',
    'Windy',
    'Cold',
    'Cloudy',
    'Mostly cloudy',
    'Mostly cloudy',
    'Partly cloudy',
    'Partly cloudy',
    'Clear',
    'Sunny',
    'Fair',
    'Fair',
    'Mixed rain and hail',
    'Hot',
    'Isolated thunderstorms',
    'Scattered thunderstorms',
    'Scattered thunderstorms',
    'Scattered showers',
    'Heavy snow',
    "Scattered snow showers",
    'Heavy snow',
    'Partly cloudy',
    'Thundershowers',
    'Snow showers',
    'Isolated thundershowers'
];

export default weatherConditionMap;